//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank.Pro6PPServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", ConfigurationName="Pro6PPServiceReference.Pro6PP_Port")]
    public interface Pro6PP_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (autocompleteRequest) of message autocompleteRequest does not match the default value (autocomplete)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/autocomplete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Q_Bank.Pro6PPServiceReference.autocompleteResponse autocomplete(Q_Bank.Pro6PPServiceReference.autocompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/autocomplete", ReplyAction="*")]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.autocompleteResponse> autocompleteAsync(Q_Bank.Pro6PPServiceReference.autocompleteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (suggestRequest) of message suggestRequest does not match the default value (suggest)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/suggest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Q_Bank.Pro6PPServiceReference.suggestResponse suggest(Q_Bank.Pro6PPServiceReference.suggestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/suggest", ReplyAction="*")]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.suggestResponse> suggestAsync(Q_Bank.Pro6PPServiceReference.suggestRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (rangeRequest) of message rangeRequest does not match the default value (range)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/range", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Q_Bank.Pro6PPServiceReference.rangeResponse range(Q_Bank.Pro6PPServiceReference.rangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/range", ReplyAction="*")]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.rangeResponse> rangeAsync(Q_Bank.Pro6PPServiceReference.rangeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (reverseRequest) of message reverseRequest does not match the default value (reverse)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/reverse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Q_Bank.Pro6PPServiceReference.reverseResponse reverse(Q_Bank.Pro6PPServiceReference.reverseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/reverse", ReplyAction="*")]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.reverseResponse> reverseAsync(Q_Bank.Pro6PPServiceReference.reverseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (feedbackRequest) of message feedbackRequest does not match the default value (feedback)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/feedback", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Q_Bank.Pro6PPServiceReference.feedbackResponse feedback(Q_Bank.Pro6PPServiceReference.feedbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.pro6pp.nl/v1/feedback", ReplyAction="*")]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.feedbackResponse> feedbackAsync(Q_Bank.Pro6PPServiceReference.feedbackRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nl_sixppField;
        
        private int nl_fourppField;
        
        private bool nl_fourppFieldSpecified;
        
        private string streetField;
        
        private string streetnumbersField;
        
        private string cityField;
        
        private string municipalityField;
        
        private string provinceField;
        
        private string latField;
        
        private string lngField;
        
        private string areacodeField;
        
        /// <remarks/>
        public string nl_sixpp {
            get {
                return this.nl_sixppField;
            }
            set {
                this.nl_sixppField = value;
                this.RaisePropertyChanged("nl_sixpp");
            }
        }
        
        /// <remarks/>
        public int nl_fourpp {
            get {
                return this.nl_fourppField;
            }
            set {
                this.nl_fourppField = value;
                this.RaisePropertyChanged("nl_fourpp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nl_fourppSpecified {
            get {
                return this.nl_fourppFieldSpecified;
            }
            set {
                this.nl_fourppFieldSpecified = value;
                this.RaisePropertyChanged("nl_fourppSpecified");
            }
        }
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        public string streetnumbers {
            get {
                return this.streetnumbersField;
            }
            set {
                this.streetnumbersField = value;
                this.RaisePropertyChanged("streetnumbers");
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        public string municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
                this.RaisePropertyChanged("municipality");
            }
        }
        
        /// <remarks/>
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("province");
            }
        }
        
        /// <remarks/>
        public string lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }
        
        /// <remarks/>
        public string lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
                this.RaisePropertyChanged("lng");
            }
        }
        
        /// <remarks/>
        public string areacode {
            get {
                return this.areacodeField;
            }
            set {
                this.areacodeField = value;
                this.RaisePropertyChanged("areacode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl")]
    public partial class FeedbackResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl")]
    public partial class ReverseResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int precisionField;
        
        private string provinceField;
        
        private string municipalityField;
        
        private string cityField;
        
        private int nl_fourppField;
        
        private decimal latField;
        
        private decimal lngField;
        
        private string nl_sixppField;
        
        private string streetsField;
        
        /// <remarks/>
        public int precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
                this.RaisePropertyChanged("precision");
            }
        }
        
        /// <remarks/>
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("province");
            }
        }
        
        /// <remarks/>
        public string municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
                this.RaisePropertyChanged("municipality");
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        public int nl_fourpp {
            get {
                return this.nl_fourppField;
            }
            set {
                this.nl_fourppField = value;
                this.RaisePropertyChanged("nl_fourpp");
            }
        }
        
        /// <remarks/>
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }
        
        /// <remarks/>
        public decimal lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
                this.RaisePropertyChanged("lng");
            }
        }
        
        /// <remarks/>
        public string nl_sixpp {
            get {
                return this.nl_sixppField;
            }
            set {
                this.nl_sixppField = value;
                this.RaisePropertyChanged("nl_sixpp");
            }
        }
        
        /// <remarks/>
        public string streets {
            get {
                return this.streetsField;
            }
            set {
                this.streetsField = value;
                this.RaisePropertyChanged("streets");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl")]
    public partial class RangeResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nl_fourppField;
        
        private decimal latField;
        
        private decimal lngField;
        
        private int distanceField;
        
        /// <remarks/>
        public int nl_fourpp {
            get {
                return this.nl_fourppField;
            }
            set {
                this.nl_fourppField = value;
                this.RaisePropertyChanged("nl_fourpp");
            }
        }
        
        /// <remarks/>
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }
        
        /// <remarks/>
        public decimal lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
                this.RaisePropertyChanged("lng");
            }
        }
        
        /// <remarks/>
        public int distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("distance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl")]
    public partial class suggestResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string city_keyField;
        
        private string cityField;
        
        private string official_cityField;
        
        private string nl_fourppsField;
        
        private string provinceField;
        
        private string streetField;
        
        private string nl_sixppsField;
        
        private decimal latField;
        
        private decimal lngField;
        
        /// <remarks/>
        public string city_key {
            get {
                return this.city_keyField;
            }
            set {
                this.city_keyField = value;
                this.RaisePropertyChanged("city_key");
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        public string official_city {
            get {
                return this.official_cityField;
            }
            set {
                this.official_cityField = value;
                this.RaisePropertyChanged("official_city");
            }
        }
        
        /// <remarks/>
        public string nl_fourpps {
            get {
                return this.nl_fourppsField;
            }
            set {
                this.nl_fourppsField = value;
                this.RaisePropertyChanged("nl_fourpps");
            }
        }
        
        /// <remarks/>
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("province");
            }
        }
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        public string nl_sixpps {
            get {
                return this.nl_sixppsField;
            }
            set {
                this.nl_sixppsField = value;
                this.RaisePropertyChanged("nl_sixpps");
            }
        }
        
        /// <remarks/>
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }
        
        /// <remarks/>
        public decimal lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
                this.RaisePropertyChanged("lng");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autocompleteRequest", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class autocompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        public string auth_key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=1)]
        public string nl_sixpp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=2)]
        public int nl_fourpp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=3)]
        public string streetnumber;
        
        public autocompleteRequest() {
        }
        
        public autocompleteRequest(string auth_key, string nl_sixpp, int nl_fourpp, string streetnumber) {
            this.auth_key = auth_key;
            this.nl_sixpp = nl_sixpp;
            this.nl_fourpp = nl_fourpp;
            this.streetnumber = streetnumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autocompleteResponse", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class autocompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result")]
        public Q_Bank.Pro6PPServiceReference.Address[] results;
        
        public autocompleteResponse() {
        }
        
        public autocompleteResponse(Q_Bank.Pro6PPServiceReference.Address[] results) {
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="suggestRequest", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class suggestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        public string auth_key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=1)]
        public string nl_city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=2)]
        public string city_key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=3)]
        public string street;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=4)]
        public int streetnumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=5)]
        public int page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=6)]
        public int per_page;
        
        public suggestRequest() {
        }
        
        public suggestRequest(string auth_key, string nl_city, string city_key, string street, int streetnumber, int page, int per_page) {
            this.auth_key = auth_key;
            this.nl_city = nl_city;
            this.city_key = city_key;
            this.street = street;
            this.streetnumber = streetnumber;
            this.page = page;
            this.per_page = per_page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="suggestResponse", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class suggestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result")]
        public Q_Bank.Pro6PPServiceReference.suggestResult[] results;
        
        public suggestResponse() {
        }
        
        public suggestResponse(Q_Bank.Pro6PPServiceReference.suggestResult[] results) {
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rangeRequest", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class rangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        public string auth_key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=1)]
        public int nl_fourpp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=2)]
        public int range;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=3)]
        public int page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=4)]
        public int per_page;
        
        public rangeRequest() {
        }
        
        public rangeRequest(string auth_key, int nl_fourpp, int range, int page, int per_page) {
            this.auth_key = auth_key;
            this.nl_fourpp = nl_fourpp;
            this.range = range;
            this.page = page;
            this.per_page = per_page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rangeResponse", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class rangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result")]
        public Q_Bank.Pro6PPServiceReference.RangeResult[] results;
        
        public rangeResponse() {
        }
        
        public rangeResponse(Q_Bank.Pro6PPServiceReference.RangeResult[] results) {
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reverseRequest", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class reverseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        public string auth_key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=1)]
        public decimal lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=2)]
        public decimal lng;
        
        public reverseRequest() {
        }
        
        public reverseRequest(string auth_key, decimal lat, decimal lng) {
            this.auth_key = auth_key;
            this.lat = lat;
            this.lng = lng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reverseResponse", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class reverseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        public Q_Bank.Pro6PPServiceReference.ReverseResults results;
        
        public reverseResponse() {
        }
        
        public reverseResponse(Q_Bank.Pro6PPServiceReference.ReverseResults results) {
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="feedbackRequest", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class feedbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        public string auth_key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=1)]
        public string nl_sixpp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=2)]
        public string street;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=3)]
        public int streetnumber;
        
        public feedbackRequest() {
        }
        
        public feedbackRequest(string auth_key, string nl_sixpp, string street, int streetnumber) {
            this.auth_key = auth_key;
            this.nl_sixpp = nl_sixpp;
            this.street = street;
            this.streetnumber = streetnumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="feedbackResponse", WrapperNamespace="http://api.pro6pp.nl/v1/soap/api.wsdl", IsWrapped=true)]
    public partial class feedbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.pro6pp.nl/v1/soap/api.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result")]
        public Q_Bank.Pro6PPServiceReference.FeedbackResult[] results;
        
        public feedbackResponse() {
        }
        
        public feedbackResponse(Q_Bank.Pro6PPServiceReference.FeedbackResult[] results) {
            this.results = results;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Pro6PP_PortChannel : Q_Bank.Pro6PPServiceReference.Pro6PP_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Pro6PP_PortClient : System.ServiceModel.ClientBase<Q_Bank.Pro6PPServiceReference.Pro6PP_Port>, Q_Bank.Pro6PPServiceReference.Pro6PP_Port {
        
        public Pro6PP_PortClient() {
        }
        
        public Pro6PP_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Pro6PP_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Pro6PP_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Pro6PP_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Q_Bank.Pro6PPServiceReference.autocompleteResponse Q_Bank.Pro6PPServiceReference.Pro6PP_Port.autocomplete(Q_Bank.Pro6PPServiceReference.autocompleteRequest request) {
            return base.Channel.autocomplete(request);
        }
        
        public Q_Bank.Pro6PPServiceReference.Address[] autocomplete(string auth_key, string nl_sixpp, int nl_fourpp, string streetnumber) {
            Q_Bank.Pro6PPServiceReference.autocompleteRequest inValue = new Q_Bank.Pro6PPServiceReference.autocompleteRequest();
            inValue.auth_key = auth_key;
            inValue.nl_sixpp = nl_sixpp;
            inValue.nl_fourpp = nl_fourpp;
            inValue.streetnumber = streetnumber;
            Q_Bank.Pro6PPServiceReference.autocompleteResponse retVal = ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).autocomplete(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.autocompleteResponse> Q_Bank.Pro6PPServiceReference.Pro6PP_Port.autocompleteAsync(Q_Bank.Pro6PPServiceReference.autocompleteRequest request) {
            return base.Channel.autocompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.autocompleteResponse> autocompleteAsync(string auth_key, string nl_sixpp, int nl_fourpp, string streetnumber) {
            Q_Bank.Pro6PPServiceReference.autocompleteRequest inValue = new Q_Bank.Pro6PPServiceReference.autocompleteRequest();
            inValue.auth_key = auth_key;
            inValue.nl_sixpp = nl_sixpp;
            inValue.nl_fourpp = nl_fourpp;
            inValue.streetnumber = streetnumber;
            return ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).autocompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Q_Bank.Pro6PPServiceReference.suggestResponse Q_Bank.Pro6PPServiceReference.Pro6PP_Port.suggest(Q_Bank.Pro6PPServiceReference.suggestRequest request) {
            return base.Channel.suggest(request);
        }
        
        public Q_Bank.Pro6PPServiceReference.suggestResult[] suggest(string auth_key, string nl_city, string city_key, string street, int streetnumber, int page, int per_page) {
            Q_Bank.Pro6PPServiceReference.suggestRequest inValue = new Q_Bank.Pro6PPServiceReference.suggestRequest();
            inValue.auth_key = auth_key;
            inValue.nl_city = nl_city;
            inValue.city_key = city_key;
            inValue.street = street;
            inValue.streetnumber = streetnumber;
            inValue.page = page;
            inValue.per_page = per_page;
            Q_Bank.Pro6PPServiceReference.suggestResponse retVal = ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).suggest(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.suggestResponse> Q_Bank.Pro6PPServiceReference.Pro6PP_Port.suggestAsync(Q_Bank.Pro6PPServiceReference.suggestRequest request) {
            return base.Channel.suggestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.suggestResponse> suggestAsync(string auth_key, string nl_city, string city_key, string street, int streetnumber, int page, int per_page) {
            Q_Bank.Pro6PPServiceReference.suggestRequest inValue = new Q_Bank.Pro6PPServiceReference.suggestRequest();
            inValue.auth_key = auth_key;
            inValue.nl_city = nl_city;
            inValue.city_key = city_key;
            inValue.street = street;
            inValue.streetnumber = streetnumber;
            inValue.page = page;
            inValue.per_page = per_page;
            return ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).suggestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Q_Bank.Pro6PPServiceReference.rangeResponse Q_Bank.Pro6PPServiceReference.Pro6PP_Port.range(Q_Bank.Pro6PPServiceReference.rangeRequest request) {
            return base.Channel.range(request);
        }
        
        public Q_Bank.Pro6PPServiceReference.RangeResult[] range(string auth_key, int nl_fourpp, int range1, int page, int per_page) {
            Q_Bank.Pro6PPServiceReference.rangeRequest inValue = new Q_Bank.Pro6PPServiceReference.rangeRequest();
            inValue.auth_key = auth_key;
            inValue.nl_fourpp = nl_fourpp;
            inValue.range = range1;
            inValue.page = page;
            inValue.per_page = per_page;
            Q_Bank.Pro6PPServiceReference.rangeResponse retVal = ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).range(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.rangeResponse> Q_Bank.Pro6PPServiceReference.Pro6PP_Port.rangeAsync(Q_Bank.Pro6PPServiceReference.rangeRequest request) {
            return base.Channel.rangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.rangeResponse> rangeAsync(string auth_key, int nl_fourpp, int range, int page, int per_page) {
            Q_Bank.Pro6PPServiceReference.rangeRequest inValue = new Q_Bank.Pro6PPServiceReference.rangeRequest();
            inValue.auth_key = auth_key;
            inValue.nl_fourpp = nl_fourpp;
            inValue.range = range;
            inValue.page = page;
            inValue.per_page = per_page;
            return ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).rangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Q_Bank.Pro6PPServiceReference.reverseResponse Q_Bank.Pro6PPServiceReference.Pro6PP_Port.reverse(Q_Bank.Pro6PPServiceReference.reverseRequest request) {
            return base.Channel.reverse(request);
        }
        
        public Q_Bank.Pro6PPServiceReference.ReverseResults reverse(string auth_key, decimal lat, decimal lng) {
            Q_Bank.Pro6PPServiceReference.reverseRequest inValue = new Q_Bank.Pro6PPServiceReference.reverseRequest();
            inValue.auth_key = auth_key;
            inValue.lat = lat;
            inValue.lng = lng;
            Q_Bank.Pro6PPServiceReference.reverseResponse retVal = ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).reverse(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.reverseResponse> Q_Bank.Pro6PPServiceReference.Pro6PP_Port.reverseAsync(Q_Bank.Pro6PPServiceReference.reverseRequest request) {
            return base.Channel.reverseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.reverseResponse> reverseAsync(string auth_key, decimal lat, decimal lng) {
            Q_Bank.Pro6PPServiceReference.reverseRequest inValue = new Q_Bank.Pro6PPServiceReference.reverseRequest();
            inValue.auth_key = auth_key;
            inValue.lat = lat;
            inValue.lng = lng;
            return ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).reverseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Q_Bank.Pro6PPServiceReference.feedbackResponse Q_Bank.Pro6PPServiceReference.Pro6PP_Port.feedback(Q_Bank.Pro6PPServiceReference.feedbackRequest request) {
            return base.Channel.feedback(request);
        }
        
        public Q_Bank.Pro6PPServiceReference.FeedbackResult[] feedback(string auth_key, string nl_sixpp, string street, int streetnumber) {
            Q_Bank.Pro6PPServiceReference.feedbackRequest inValue = new Q_Bank.Pro6PPServiceReference.feedbackRequest();
            inValue.auth_key = auth_key;
            inValue.nl_sixpp = nl_sixpp;
            inValue.street = street;
            inValue.streetnumber = streetnumber;
            Q_Bank.Pro6PPServiceReference.feedbackResponse retVal = ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).feedback(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.feedbackResponse> Q_Bank.Pro6PPServiceReference.Pro6PP_Port.feedbackAsync(Q_Bank.Pro6PPServiceReference.feedbackRequest request) {
            return base.Channel.feedbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<Q_Bank.Pro6PPServiceReference.feedbackResponse> feedbackAsync(string auth_key, string nl_sixpp, string street, int streetnumber) {
            Q_Bank.Pro6PPServiceReference.feedbackRequest inValue = new Q_Bank.Pro6PPServiceReference.feedbackRequest();
            inValue.auth_key = auth_key;
            inValue.nl_sixpp = nl_sixpp;
            inValue.street = street;
            inValue.streetnumber = streetnumber;
            return ((Q_Bank.Pro6PPServiceReference.Pro6PP_Port)(this)).feedbackAsync(inValue);
        }
    }
}
