//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.accounts = new HashSet<account>();
            this.customeraddresses = new HashSet<customeraddress>();
            this.customeremails = new HashSet<customeremail>();
            this.customerloginlogs = new HashSet<customerloginlog>();
            this.customermessages = new HashSet<customermessage>();
            this.customerphones = new HashSet<customerphone>();
        }
    
        public int customerId { get; set; }
        public string bsn { get; set; }
        public bool active { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public System.DateTime birthDate { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string key { get; set; }
        public System.DateTime registerDatetime { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual ICollection<customeraddress> customeraddresses { get; set; }
        public virtual ICollection<customeremail> customeremails { get; set; }
        public virtual ICollection<customerloginlog> customerloginlogs { get; set; }
        public virtual ICollection<customermessage> customermessages { get; set; }
        public virtual ICollection<customerphone> customerphones { get; set; }
    }
}
