//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class customeraddress
    {
        public int customeAddressId { get; set; }
        public int customerId { get; set; }
        public short active { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string number { get; set; }
        public string zipcode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
