//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeephone
    {
        public int employeePhoneId { get; set; }
        public int employeeId { get; set; }
        public int phoneTypeId { get; set; }
        public string phonenumber { get; set; }
        public bool active { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual phonetype phonetype { get; set; }
    }
}
