//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeemessage
    {
        public int customerMessageId { get; set; }
        public int employeeId { get; set; }
        public string subject { get; set; }
        public string messageText { get; set; }
        public Nullable<bool> read { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
