//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginlog
    {
        public int loginId { get; set; }
        public int userId { get; set; }
        public string ip { get; set; }
        public System.DateTime datetimeLogin { get; set; }
    
        public virtual user user { get; set; }
    }
}
