//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Q_BANKEntities : DbContext
    {
        public Q_BANKEntities()
            : base("name=Q_BANKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<accounttype> accounttypes { get; set; }
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<email> emails { get; set; }
        public virtual DbSet<loginlog> loginlogs { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<phone> phones { get; set; }
        public virtual DbSet<phonetype> phonetypes { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<transactionstatu> transactionstatus { get; set; }
        public virtual DbSet<transactiontype> transactiontypes { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
