//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Q_BANKEntities : DbContext
    {
        public Q_BANKEntities()
            : base("name=Q_BANKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<accounttype> accounttypes { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customeraddress> customeraddresses { get; set; }
        public virtual DbSet<customeremail> customeremails { get; set; }
        public virtual DbSet<customerloginlog> customerloginlogs { get; set; }
        public virtual DbSet<customermessage> customermessages { get; set; }
        public virtual DbSet<customerphone> customerphones { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employeeaddress> employeeaddresses { get; set; }
        public virtual DbSet<employeeemail> employeeemails { get; set; }
        public virtual DbSet<employeeloginlog> employeeloginlogs { get; set; }
        public virtual DbSet<employeemessage> employeemessages { get; set; }
        public virtual DbSet<employeephone> employeephones { get; set; }
        public virtual DbSet<phonetype> phonetypes { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<transactionqueue> transactionqueues { get; set; }
        public virtual DbSet<transactionstatu> transactionstatus { get; set; }
    }
}
