//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.accounts = new HashSet<account>();
            this.addresses = new HashSet<address>();
            this.emails = new HashSet<email>();
            this.loginlogs = new HashSet<loginlog>();
            this.messages = new HashSet<message>();
            this.phones = new HashSet<phone>();
        }
    
        public int userId { get; set; }
        public int roleId { get; set; }
        public string bsn { get; set; }
        public short active { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public System.DateTime birthDate { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime registerDatetime { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<email> emails { get; set; }
        public virtual ICollection<loginlog> loginlogs { get; set; }
        public virtual ICollection<message> messages { get; set; }
        public virtual ICollection<phone> phones { get; set; }
        public virtual role role { get; set; }
    }
}
